### PR TITLE
Main Menu MVP

### PR DESCRIPTION
**Pull request by mis825**
### Important

Don't plan on merging this yet as I have to resolve the merge conflicts first.

_However!_

Here is the first pass of our _brand-new_ main menu!

### Instructions:

1. Double-click the _new_ `MainMenu` scene
2. Start the scene
3. Interact with the three buttons
4. Press play to load the options

### CODE REVIEW

**Comment by tituswhang** [comment]
Main menu looks great! One thing I would add is to allow the player to return to the main menu when they press `esc` on the keyboard. Other than that, stellar work!

**Comment by tituswhang** [comment]
Pulled new changes to the `boomboom` branch and exported it. Everything works great! The game starts with the menu, settings work as intended, the quit button exits out of the game. Pressing escape pulls up the pause menu and stops time, and lets the user return to the main menu. Good job!

**Comment by tituswhang** [comment]
Lmk if these changes are final so I can merge this pull request to master :)

**Comment by mis825** [comment]
> Lmk if these changes are final so I can merge this pull request to master :)

These changes are ready to be merged 👍

**Review by tituswhang — APPROVED** [review]

**Pull request merged**
